version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=studenci_2020
    ports:
      - "27017:27017"
    restart: unless-stopped

  payara:
    image: payara/server-full:5.2022.5
    volumes:
      - ./deployments:/opt/payara/appserver/glassfish/domains/domain1/autodeploy
    container_name: payara
    environment:
      - PAYARA_ARGS=--debug
    ports:
      - "4848:4848"
      - "8080:8080"
      - "9009:9009"
    restart: unless-stopped
